class SendMessageExeptions(Exception):
    """Исключение возникает при отправке сообщений."""

    pass
